
services:
  main:
    build: .
    tty: true
    develop:
      watch:
        - action: sync
          path: ./src
          target: /home/datapolicy/src
    volumes:
      - type: bind
        source: ./data
        target: /home/datapolicy/data
        